###//- recuperar todos los proyectos
GET http://localhost:3000/api/proyectos 

### //- crear un nuevo proyecto
POST http://localhost:3000/api/proyectos 
Content-Type: application/json

{
    "titulo":"Prueba1",
    "descripcion":"Descripcion de prueba",
    "url":"http://www.google.es",
    "cliente":"Google",
    "url_cliente":"http://www.google.es"

}

### //- editar un proyecto
PUT http://localhost:3000/api/proyectos  

### //- borrar proyecto
DELETE http://localhost:3000/api/proyectos 
