###//- recuperar todos los proyectos
GET http://localhost:3000/api/proyectos 
access-token:eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyIjoiSXbDoW4iLCJjcmVhdGVkX2F0IjoxNjE3NjQ2MDI1LCJleHBpcmVkX2F0IjoxNjE3NjQ2MzI1fQ.W9yMlTq28iu_Rm5I3vGJHWOJY26-B_zErxsRKgzvQrc

### //- crear un nuevo proyecto
POST http://localhost:3000/api/proyectos 
Content-Type: application/json

{
    "titulo":"Prueba1",
    "descripcion":"Descripcion de prueba",
    "url":"http://www.google.es",
    "cliente":"Google",
    "url_cliente":"http://www.google.es"

}

### //- editar un proyecto
PUT http://localhost:3000/api/proyectos/6066f34b2591152e20359cd8  
Content-Type: application/json

{
    "titulo":"Editado de prueba",
    "descripcion":"Descripcion de prueba",
    "url":"http://www.google.es",
    "cliente":"Google",
    "url_cliente":"http://www.google.es"

}

### //- borrar proyecto
DELETE http://localhost:3000/api/proyectos/6066fc04b12b230bc480b0cf 

###
GET http://localhost:3000/api/token

### PRODUCCION

GET https://myportfolioback.herokuapp.com/api/proyectos
access-token:eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyIjoiSXbDoW4iLCJjcmVhdGVkX2F0IjoxNjE3NjQ2OTQwLCJleHBpcmVkX2F0IjoxNjE3NjQ3MjQwfQ._rtaG0_VL_oaXiA-96rFNm6NQfilDCpzx_H9WKwOpTk

### 
GET https://myportfolioback.herokuapp.com/api/token


